version: "3.9"

services:
  web:
    image: nginx:1.21.6-alpine
    ports:
      - 8890:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: test-symfony-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.7.3-focal
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    # ports:
    #   - 3308:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
volumes:
  db-data: